### PR TITLE
:sparkles: Update analyzer, update labels, remove facts rules

### LINKED ISSUE #79: Explicit (wildcard) source labels.
For rulesets that contain rules with a combination of labels for a target.  Some rules have explicit sources but others pertain to all sources. In windup, the Rule without an explicit source, is matched for all sources.

Consider the following use case based on Shim generated rules.

Labels selected by the user (in the UI):
- konveyor.io/source=S1
- konveyor.io/target=T1

Generated ruleset.

Rule A:
 - labels
   - konveyor.io/source=S1
   - konveyor.io/target=T1
 
Rule B:
 - labels
   - konveyor.io/target=T1

Rule C:
- labels
   - konveyor.io/source=**S2**
   - konveyor.io/target=T1

The intention is for rules A & B (but not C) be matched. How to build a selector expression to accomplish this?

A selector of `(konveyor.io/source=S1 && konveyor.io/target=T1)` will only match Rule A.
A selector of `(konveyor.io/source && konveyor.io/target=T1)` will match all (3) rules A,B,C which is not intended.

---

Potential solution:

The shim generated Rule-B as:

Rule B:
- labels
  - konveyor.io/source
  - konveyor.io/target=T1

### PR DESCRIPTION
**Pull request by pranavgaikwad**
Analyzer PR: 252
Fixes #79

### CODE REVIEW

**Comment by fabianvf** [comment]
@pranavgaikwad what's up with that pass rate?

**Comment by pranavgaikwad** [comment]
@fabianvf lol, I need to update this again, there was a brief period of time when analyzer was broken and I seem to have updated the deps exactly then

**Comment by pranavgaikwad** [comment]
This shouldn't be failing, investigating...moving to draft until I figure out.

**Review by shawn-hurley — APPROVED** [review]
LGTM for right now

**Pull request merged**
