### PR TITLE
Convert to IMPORT instead of PACKAGE

### PR DESCRIPTION
**Pull request by jmle**
Fixes https://github.com/konveyor/analyzer-lsp/issues/413

### CODE REVIEW

**Comment by shawn-hurley** [comment]
We need to make sure that this does cause other issues, like finding matches when it shouldn't. 

This was the initial reason to move to the package. IDK did how to do this systematically, but @pranavgaikwad did some great work putting it together. 

If this solves this, I will be happy, but did want to make sure that we don't flip-flop issues :)

**Comment by jmle** [comment]
@shawn-hurley ...aaand then I just found [this rule](https://github.com/konveyor/rulesets/blob/main/default/generated/eap7/70-jboss-eap5and6to7-java.windup.yaml#L121), which doesn't work with `IMPORT` but does with `PACKAGE`...
```yaml
    - java.referenced:
        location: IMPORT
        pattern: javax.enterprise.deploy*
```

**Comment by jmle** [comment]
Last success rate: 80.58% (1905/2364)

**Review by pranavgaikwad — APPROVED** [review]

**Comment by shawn-hurley** [comment]
I think that, for now, we take this as is; IF we find more and more where it becomes a problem, I think we open a new one and figure out how to do both and then make sure that we can filter out the results that shouldn't match.

**Review by fabianvf — APPROVED** [review]

**Review by aufi — APPROVED** [review]

**Comment by jmle** [comment]
I have merged it, although I guess that we'll have to see whether we want to keep using the shim for making changes in the rulesets, or if we want to change the rulesets directly instead.

**Comment by fabianvf** [comment]
I think if we can we'll want to keep making changes to the shim, since that will also help users with custom rulesets

**Pull request merged**
