### PR TITLE
:sparkles: Rules conversion fixes for adding include=always label 

### PR DESCRIPTION
**Pull request by pranavgaikwad**
Also flattening the rules by default, as thats what we are doing for generating rulesets for seeding

### CODE REVIEW

**Review by fabianvf — APPROVED** [review]

**Review by fabianvf — CHANGES_REQUESTED** [review]
Wait, pause. Looks like that killed our pass rate: Overall success rate: 61.47% (576/937)

**Comment by fabianvf** [comment]
actually looks like they didn't complete at all, rekicking. Also we should have failed with an exit code instead of passing, that's an issue

**Comment by pranavgaikwad** [comment]
I dont think this PR affects the rate, this is just to add labels

**Review by fabianvf — APPROVED** [review]
Yeah just looks like an error during execution

**Pull request merged**
